version: "1.0"
name: 流水线-202609050421
displayName: 流水线-202609050421
stages:
- name: 未命名
  displayName: 未命名
  strategy: naturally
  trigger: auto
  steps:
  - step: image-build-plus@buildkitd
    name: 24fe2609
    displayName: 镜像构建 2.0
    tag: "${GITEE_PIPELINE_BUILD_NUMBER}"
    dockerfile: ./Dockerfile
    context: ""
    artifacts: []
    isCache: false
    processorType:
    - amd64
    strategy:
      retry: "0"
      resource:
        cpu: "8"
        memory: "16"
triggers:
  trigger: auto
  push:
    branches:
      prefix:
      - ""
      precise: []
      include: []
notify: []
