name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build & Export tar 落盘
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          outputs: type=docker,dest=./mcserver.tar

      - name: 查看生成文件
        run: ls -lh ./

      - name: 上传为Github Actions制品
        uses: actions/upload-artifact@v4
        with:
          name: mcserver-image-tar
          path: ./mcserver.tar
